{{- range .Values.edge.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rollcall-go.instance.name" (dict "root" $ "instance" .) }}-secret
  labels:
    {{- include "rollcall-go.instance.labels" (dict "root" $ "instance" .) | nindent 4 }}
type: Opaque
stringData:
  EDGE_USERNAME: {{ .config.edgeUsername | quote }}
  EDGE_PASSWORD: {{ .config.edgePassword | quote }}
  EDGE_CENTER_SERVER_SECRET: {{ .config.centerServerSecret | default "" | quote }}
  TG_BOT_TOKEN: {{ .config.tgBotToken | default "" | quote }}
  TG_CHAT_ID: {{ .config.tgChatId | default "" | quote }}
{{- end }}
