{{- range .Values.edge.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollcall-go.instance.name" (dict "root" $ "instance" .) }}
  labels:
    {{- include "rollcall-go.instance.labels" (dict "root" $ "instance" .) | nindent 4 }}
spec:
  type: {{ $.Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $.Values.edge.servicePort | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rollcall-go.instance.selectorLabels" (dict "root" $ "instance" .) | nindent 4 }}
{{- end }}
