// Code generated by Kitex v0.16.2. DO NOT EDIT.

package edgeservice

import (
	"context"
	edge "github.com/Auto-CQUPT-Plan/rollcall-go/internal/rpc/kitex_gen/edge"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Health(ctx context.Context, callOptions ...callopt.Option) (r *edge.HealthResponse, err error)
	GetRollcalls(ctx context.Context, callOptions ...callopt.Option) (r []*edge.Rollcall, err error)
	GetPauseState(ctx context.Context, callOptions ...callopt.Option) (r *edge.PauseState, err error)
	SetPause(ctx context.Context, req *edge.SetPauseRequest, callOptions ...callopt.Option) (r *edge.SetPauseResponse, err error)
	QRCheckin(ctx context.Context, req *edge.QRCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error)
	NumberCheckin(ctx context.Context, req *edge.NumberCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error)
	LocationCheckin(ctx context.Context, req *edge.LocationCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error)
	BatchQRCheckin(ctx context.Context, req *edge.BatchQRCheckinRequest, callOptions ...callopt.Option) (r *edge.BatchQRCheckinResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kEdgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEdgeServiceClient struct {
	*kClient
}

func (p *kEdgeServiceClient) Health(ctx context.Context, callOptions ...callopt.Option) (r *edge.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Health(ctx)
}

func (p *kEdgeServiceClient) GetRollcalls(ctx context.Context, callOptions ...callopt.Option) (r []*edge.Rollcall, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRollcalls(ctx)
}

func (p *kEdgeServiceClient) GetPauseState(ctx context.Context, callOptions ...callopt.Option) (r *edge.PauseState, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPauseState(ctx)
}

func (p *kEdgeServiceClient) SetPause(ctx context.Context, req *edge.SetPauseRequest, callOptions ...callopt.Option) (r *edge.SetPauseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetPause(ctx, req)
}

func (p *kEdgeServiceClient) QRCheckin(ctx context.Context, req *edge.QRCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QRCheckin(ctx, req)
}

func (p *kEdgeServiceClient) NumberCheckin(ctx context.Context, req *edge.NumberCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.NumberCheckin(ctx, req)
}

func (p *kEdgeServiceClient) LocationCheckin(ctx context.Context, req *edge.LocationCheckinRequest, callOptions ...callopt.Option) (r *edge.OperationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LocationCheckin(ctx, req)
}

func (p *kEdgeServiceClient) BatchQRCheckin(ctx context.Context, req *edge.BatchQRCheckinRequest, callOptions ...callopt.Option) (r *edge.BatchQRCheckinResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchQRCheckin(ctx, req)
}
