// Code generated by Kitex v0.16.2. DO NOT EDIT.

package edgeservice

import (
	"context"
	"errors"
	edge "github.com/Auto-CQUPT-Plan/rollcall-go/internal/rpc/kitex_gen/edge"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Health": kitex.NewMethodInfo(
		healthHandler,
		newEdgeServiceHealthArgs,
		newEdgeServiceHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRollcalls": kitex.NewMethodInfo(
		getRollcallsHandler,
		newEdgeServiceGetRollcallsArgs,
		newEdgeServiceGetRollcallsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPauseState": kitex.NewMethodInfo(
		getPauseStateHandler,
		newEdgeServiceGetPauseStateArgs,
		newEdgeServiceGetPauseStateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetPause": kitex.NewMethodInfo(
		setPauseHandler,
		newEdgeServiceSetPauseArgs,
		newEdgeServiceSetPauseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QRCheckin": kitex.NewMethodInfo(
		qRCheckinHandler,
		newEdgeServiceQRCheckinArgs,
		newEdgeServiceQRCheckinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"NumberCheckin": kitex.NewMethodInfo(
		numberCheckinHandler,
		newEdgeServiceNumberCheckinArgs,
		newEdgeServiceNumberCheckinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LocationCheckin": kitex.NewMethodInfo(
		locationCheckinHandler,
		newEdgeServiceLocationCheckinArgs,
		newEdgeServiceLocationCheckinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchQRCheckin": kitex.NewMethodInfo(
		batchQRCheckinHandler,
		newEdgeServiceBatchQRCheckinArgs,
		newEdgeServiceBatchQRCheckinResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	edgeServiceServiceInfo                = NewServiceInfo()
	edgeServiceServiceInfoForClient       = NewServiceInfoForClient()
	edgeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return edgeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return edgeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return edgeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EdgeService"
	handlerType := (*edge.EdgeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "edge",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*edge.EdgeServiceHealthArgs)
	realResult := result.(*edge.EdgeServiceHealthResult)
	success, err := handler.(edge.EdgeService).Health(ctx)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceHealthArgs() interface{} {
	return edge.NewEdgeServiceHealthArgs()
}

func newEdgeServiceHealthResult() interface{} {
	return edge.NewEdgeServiceHealthResult()
}

func getRollcallsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*edge.EdgeServiceGetRollcallsArgs)
	realResult := result.(*edge.EdgeServiceGetRollcallsResult)
	success, err := handler.(edge.EdgeService).GetRollcalls(ctx)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceGetRollcallsArgs() interface{} {
	return edge.NewEdgeServiceGetRollcallsArgs()
}

func newEdgeServiceGetRollcallsResult() interface{} {
	return edge.NewEdgeServiceGetRollcallsResult()
}

func getPauseStateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*edge.EdgeServiceGetPauseStateArgs)
	realResult := result.(*edge.EdgeServiceGetPauseStateResult)
	success, err := handler.(edge.EdgeService).GetPauseState(ctx)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceGetPauseStateArgs() interface{} {
	return edge.NewEdgeServiceGetPauseStateArgs()
}

func newEdgeServiceGetPauseStateResult() interface{} {
	return edge.NewEdgeServiceGetPauseStateResult()
}

func setPauseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*edge.EdgeServiceSetPauseArgs)
	realResult := result.(*edge.EdgeServiceSetPauseResult)
	success, err := handler.(edge.EdgeService).SetPause(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceSetPauseArgs() interface{} {
	return edge.NewEdgeServiceSetPauseArgs()
}

func newEdgeServiceSetPauseResult() interface{} {
	return edge.NewEdgeServiceSetPauseResult()
}

func qRCheckinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*edge.EdgeServiceQRCheckinArgs)
	realResult := result.(*edge.EdgeServiceQRCheckinResult)
	success, err := handler.(edge.EdgeService).QRCheckin(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceQRCheckinArgs() interface{} {
	return edge.NewEdgeServiceQRCheckinArgs()
}

func newEdgeServiceQRCheckinResult() interface{} {
	return edge.NewEdgeServiceQRCheckinResult()
}

func numberCheckinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*edge.EdgeServiceNumberCheckinArgs)
	realResult := result.(*edge.EdgeServiceNumberCheckinResult)
	success, err := handler.(edge.EdgeService).NumberCheckin(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceNumberCheckinArgs() interface{} {
	return edge.NewEdgeServiceNumberCheckinArgs()
}

func newEdgeServiceNumberCheckinResult() interface{} {
	return edge.NewEdgeServiceNumberCheckinResult()
}

func locationCheckinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*edge.EdgeServiceLocationCheckinArgs)
	realResult := result.(*edge.EdgeServiceLocationCheckinResult)
	success, err := handler.(edge.EdgeService).LocationCheckin(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceLocationCheckinArgs() interface{} {
	return edge.NewEdgeServiceLocationCheckinArgs()
}

func newEdgeServiceLocationCheckinResult() interface{} {
	return edge.NewEdgeServiceLocationCheckinResult()
}

func batchQRCheckinHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*edge.EdgeServiceBatchQRCheckinArgs)
	realResult := result.(*edge.EdgeServiceBatchQRCheckinResult)
	success, err := handler.(edge.EdgeService).BatchQRCheckin(ctx, realArg.Req)
	if err != nil {
		switch v := err.(type) {
		case *edge.ServiceException:
			realResult.Ex = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newEdgeServiceBatchQRCheckinArgs() interface{} {
	return edge.NewEdgeServiceBatchQRCheckinArgs()
}

func newEdgeServiceBatchQRCheckinResult() interface{} {
	return edge.NewEdgeServiceBatchQRCheckinResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Health(ctx context.Context) (r *edge.HealthResponse, err error) {
	var _args edge.EdgeServiceHealthArgs
	var _result edge.EdgeServiceHealthResult
	if err = p.c.Call(ctx, "Health", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRollcalls(ctx context.Context) (r []*edge.Rollcall, err error) {
	var _args edge.EdgeServiceGetRollcallsArgs
	var _result edge.EdgeServiceGetRollcallsResult
	if err = p.c.Call(ctx, "GetRollcalls", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPauseState(ctx context.Context) (r *edge.PauseState, err error) {
	var _args edge.EdgeServiceGetPauseStateArgs
	var _result edge.EdgeServiceGetPauseStateResult
	if err = p.c.Call(ctx, "GetPauseState", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetPause(ctx context.Context, req *edge.SetPauseRequest) (r *edge.SetPauseResponse, err error) {
	var _args edge.EdgeServiceSetPauseArgs
	_args.Req = req
	var _result edge.EdgeServiceSetPauseResult
	if err = p.c.Call(ctx, "SetPause", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QRCheckin(ctx context.Context, req *edge.QRCheckinRequest) (r *edge.OperationResponse, err error) {
	var _args edge.EdgeServiceQRCheckinArgs
	_args.Req = req
	var _result edge.EdgeServiceQRCheckinResult
	if err = p.c.Call(ctx, "QRCheckin", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) NumberCheckin(ctx context.Context, req *edge.NumberCheckinRequest) (r *edge.OperationResponse, err error) {
	var _args edge.EdgeServiceNumberCheckinArgs
	_args.Req = req
	var _result edge.EdgeServiceNumberCheckinResult
	if err = p.c.Call(ctx, "NumberCheckin", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LocationCheckin(ctx context.Context, req *edge.LocationCheckinRequest) (r *edge.OperationResponse, err error) {
	var _args edge.EdgeServiceLocationCheckinArgs
	_args.Req = req
	var _result edge.EdgeServiceLocationCheckinResult
	if err = p.c.Call(ctx, "LocationCheckin", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchQRCheckin(ctx context.Context, req *edge.BatchQRCheckinRequest) (r *edge.BatchQRCheckinResponse, err error) {
	var _args edge.EdgeServiceBatchQRCheckinArgs
	_args.Req = req
	var _result edge.EdgeServiceBatchQRCheckinResult
	if err = p.c.Call(ctx, "BatchQRCheckin", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.Ex != nil:
		return r, _result.Ex
	}
	return _result.GetSuccess(), nil
}
