// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package edge

import (
	"context"
	"fmt"
)

type Rollcall struct {
	RollcallId   int64  `thrift:"rollcall_id,1" frugal:"1,default,i64" json:"rollcall_id"`
	Source       string `thrift:"source,2" frugal:"2,default,string" json:"source"`
	Status       string `thrift:"status,3" frugal:"3,default,string" json:"status"`
	CourseTitle  string `thrift:"course_title,4" frugal:"4,default,string" json:"course_title"`
	RollcallTime string `thrift:"rollcall_time,5" frugal:"5,default,string" json:"rollcall_time"`
}

func NewRollcall() *Rollcall {
	return &Rollcall{}
}

func (p *Rollcall) InitDefault() {
}

func (p *Rollcall) GetRollcallId() (v int64) {
	return p.RollcallId
}

func (p *Rollcall) GetSource() (v string) {
	return p.Source
}

func (p *Rollcall) GetStatus() (v string) {
	return p.Status
}

func (p *Rollcall) GetCourseTitle() (v string) {
	return p.CourseTitle
}

func (p *Rollcall) GetRollcallTime() (v string) {
	return p.RollcallTime
}
func (p *Rollcall) SetRollcallId(val int64) {
	p.RollcallId = val
}
func (p *Rollcall) SetSource(val string) {
	p.Source = val
}
func (p *Rollcall) SetStatus(val string) {
	p.Status = val
}
func (p *Rollcall) SetCourseTitle(val string) {
	p.CourseTitle = val
}
func (p *Rollcall) SetRollcallTime(val string) {
	p.RollcallTime = val
}

func (p *Rollcall) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Rollcall(%+v)", *p)
}

var fieldIDToName_Rollcall = map[int16]string{
	1: "rollcall_id",
	2: "source",
	3: "status",
	4: "course_title",
	5: "rollcall_time",
}

type HealthResponse struct {
	Status   string `thrift:"status,1" frugal:"1,default,string" json:"status"`
	ClientId string `thrift:"client_id,2" frugal:"2,default,string" json:"client_id"`
}

func NewHealthResponse() *HealthResponse {
	return &HealthResponse{}
}

func (p *HealthResponse) InitDefault() {
}

func (p *HealthResponse) GetStatus() (v string) {
	return p.Status
}

func (p *HealthResponse) GetClientId() (v string) {
	return p.ClientId
}
func (p *HealthResponse) SetStatus(val string) {
	p.Status = val
}
func (p *HealthResponse) SetClientId(val string) {
	p.ClientId = val
}

func (p *HealthResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HealthResponse(%+v)", *p)
}

var fieldIDToName_HealthResponse = map[int16]string{
	1: "status",
	2: "client_id",
}

type PauseState struct {
	Pause bool `thrift:"pause,1" frugal:"1,default,bool" json:"pause"`
}

func NewPauseState() *PauseState {
	return &PauseState{}
}

func (p *PauseState) InitDefault() {
}

func (p *PauseState) GetPause() (v bool) {
	return p.Pause
}
func (p *PauseState) SetPause(val bool) {
	p.Pause = val
}

func (p *PauseState) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PauseState(%+v)", *p)
}

var fieldIDToName_PauseState = map[int16]string{
	1: "pause",
}

type SetPauseRequest struct {
	Pause bool `thrift:"pause,1" frugal:"1,default,bool" json:"pause"`
}

func NewSetPauseRequest() *SetPauseRequest {
	return &SetPauseRequest{}
}

func (p *SetPauseRequest) InitDefault() {
}

func (p *SetPauseRequest) GetPause() (v bool) {
	return p.Pause
}
func (p *SetPauseRequest) SetPause(val bool) {
	p.Pause = val
}

func (p *SetPauseRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetPauseRequest(%+v)", *p)
}

var fieldIDToName_SetPauseRequest = map[int16]string{
	1: "pause",
}

type SetPauseResponse struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
	Pause   bool   `thrift:"pause,2" frugal:"2,default,bool" json:"pause"`
}

func NewSetPauseResponse() *SetPauseResponse {
	return &SetPauseResponse{}
}

func (p *SetPauseResponse) InitDefault() {
}

func (p *SetPauseResponse) GetMessage() (v string) {
	return p.Message
}

func (p *SetPauseResponse) GetPause() (v bool) {
	return p.Pause
}
func (p *SetPauseResponse) SetMessage(val string) {
	p.Message = val
}
func (p *SetPauseResponse) SetPause(val bool) {
	p.Pause = val
}

func (p *SetPauseResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetPauseResponse(%+v)", *p)
}

var fieldIDToName_SetPauseResponse = map[int16]string{
	1: "message",
	2: "pause",
}

type QRCheckinRequest struct {
	RollcallId int64  `thrift:"rollcall_id,1" frugal:"1,default,i64" json:"rollcall_id"`
	Data       string `thrift:"data,2" frugal:"2,default,string" json:"data"`
}

func NewQRCheckinRequest() *QRCheckinRequest {
	return &QRCheckinRequest{}
}

func (p *QRCheckinRequest) InitDefault() {
}

func (p *QRCheckinRequest) GetRollcallId() (v int64) {
	return p.RollcallId
}

func (p *QRCheckinRequest) GetData() (v string) {
	return p.Data
}
func (p *QRCheckinRequest) SetRollcallId(val int64) {
	p.RollcallId = val
}
func (p *QRCheckinRequest) SetData(val string) {
	p.Data = val
}

func (p *QRCheckinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QRCheckinRequest(%+v)", *p)
}

var fieldIDToName_QRCheckinRequest = map[int16]string{
	1: "rollcall_id",
	2: "data",
}

type NumberCheckinRequest struct {
	RollcallId int64  `thrift:"rollcall_id,1" frugal:"1,default,i64" json:"rollcall_id"`
	NumberCode string `thrift:"number_code,2" frugal:"2,default,string" json:"number_code"`
}

func NewNumberCheckinRequest() *NumberCheckinRequest {
	return &NumberCheckinRequest{}
}

func (p *NumberCheckinRequest) InitDefault() {
}

func (p *NumberCheckinRequest) GetRollcallId() (v int64) {
	return p.RollcallId
}

func (p *NumberCheckinRequest) GetNumberCode() (v string) {
	return p.NumberCode
}
func (p *NumberCheckinRequest) SetRollcallId(val int64) {
	p.RollcallId = val
}
func (p *NumberCheckinRequest) SetNumberCode(val string) {
	p.NumberCode = val
}

func (p *NumberCheckinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NumberCheckinRequest(%+v)", *p)
}

var fieldIDToName_NumberCheckinRequest = map[int16]string{
	1: "rollcall_id",
	2: "number_code",
}

type LocationCheckinRequest struct {
	RollcallId int64   `thrift:"rollcall_id,1" frugal:"1,default,i64" json:"rollcall_id"`
	Lat        float64 `thrift:"lat,2" frugal:"2,default,double" json:"lat"`
	Lon        float64 `thrift:"lon,3" frugal:"3,default,double" json:"lon"`
}

func NewLocationCheckinRequest() *LocationCheckinRequest {
	return &LocationCheckinRequest{}
}

func (p *LocationCheckinRequest) InitDefault() {
}

func (p *LocationCheckinRequest) GetRollcallId() (v int64) {
	return p.RollcallId
}

func (p *LocationCheckinRequest) GetLat() (v float64) {
	return p.Lat
}

func (p *LocationCheckinRequest) GetLon() (v float64) {
	return p.Lon
}
func (p *LocationCheckinRequest) SetRollcallId(val int64) {
	p.RollcallId = val
}
func (p *LocationCheckinRequest) SetLat(val float64) {
	p.Lat = val
}
func (p *LocationCheckinRequest) SetLon(val float64) {
	p.Lon = val
}

func (p *LocationCheckinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LocationCheckinRequest(%+v)", *p)
}

var fieldIDToName_LocationCheckinRequest = map[int16]string{
	1: "rollcall_id",
	2: "lat",
	3: "lon",
}

type CheckinResult_ struct {
	RollcallId int64   `thrift:"rollcall_id,1" frugal:"1,default,i64" json:"rollcall_id"`
	Status     string  `thrift:"status,2" frugal:"2,default,string" json:"status"`
	Error      *string `thrift:"error,3,optional" frugal:"3,optional,string" json:"error,omitempty"`
}

func NewCheckinResult_() *CheckinResult_ {
	return &CheckinResult_{}
}

func (p *CheckinResult_) InitDefault() {
}

func (p *CheckinResult_) GetRollcallId() (v int64) {
	return p.RollcallId
}

func (p *CheckinResult_) GetStatus() (v string) {
	return p.Status
}

var CheckinResult__Error_DEFAULT string

func (p *CheckinResult_) GetError() (v string) {
	if !p.IsSetError() {
		return CheckinResult__Error_DEFAULT
	}
	return *p.Error
}
func (p *CheckinResult_) SetRollcallId(val int64) {
	p.RollcallId = val
}
func (p *CheckinResult_) SetStatus(val string) {
	p.Status = val
}
func (p *CheckinResult_) SetError(val *string) {
	p.Error = val
}

func (p *CheckinResult_) IsSetError() bool {
	return p.Error != nil
}

func (p *CheckinResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckinResult_(%+v)", *p)
}

var fieldIDToName_CheckinResult_ = map[int16]string{
	1: "rollcall_id",
	2: "status",
	3: "error",
}

type BatchQRCheckinRequest struct {
	Data string `thrift:"data,1" frugal:"1,default,string" json:"data"`
}

func NewBatchQRCheckinRequest() *BatchQRCheckinRequest {
	return &BatchQRCheckinRequest{}
}

func (p *BatchQRCheckinRequest) InitDefault() {
}

func (p *BatchQRCheckinRequest) GetData() (v string) {
	return p.Data
}
func (p *BatchQRCheckinRequest) SetData(val string) {
	p.Data = val
}

func (p *BatchQRCheckinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchQRCheckinRequest(%+v)", *p)
}

var fieldIDToName_BatchQRCheckinRequest = map[int16]string{
	1: "data",
}

type BatchQRCheckinResponse struct {
	Results []*CheckinResult_ `thrift:"results,1" frugal:"1,default,list<CheckinResult_>" json:"results"`
}

func NewBatchQRCheckinResponse() *BatchQRCheckinResponse {
	return &BatchQRCheckinResponse{}
}

func (p *BatchQRCheckinResponse) InitDefault() {
}

func (p *BatchQRCheckinResponse) GetResults() (v []*CheckinResult_) {
	return p.Results
}
func (p *BatchQRCheckinResponse) SetResults(val []*CheckinResult_) {
	p.Results = val
}

func (p *BatchQRCheckinResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BatchQRCheckinResponse(%+v)", *p)
}

var fieldIDToName_BatchQRCheckinResponse = map[int16]string{
	1: "results",
}

type OperationResponse struct {
	Message string `thrift:"message,1" frugal:"1,default,string" json:"message"`
}

func NewOperationResponse() *OperationResponse {
	return &OperationResponse{}
}

func (p *OperationResponse) InitDefault() {
}

func (p *OperationResponse) GetMessage() (v string) {
	return p.Message
}
func (p *OperationResponse) SetMessage(val string) {
	p.Message = val
}

func (p *OperationResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OperationResponse(%+v)", *p)
}

var fieldIDToName_OperationResponse = map[int16]string{
	1: "message",
}

type ServiceException struct {
	StatusCode int32  `thrift:"status_code,1" frugal:"1,default,i32" json:"status_code"`
	Error_     string `thrift:"error,2" frugal:"2,default,string" json:"error"`
}

func NewServiceException() *ServiceException {
	return &ServiceException{}
}

func (p *ServiceException) InitDefault() {
}

func (p *ServiceException) GetStatusCode() (v int32) {
	return p.StatusCode
}

func (p *ServiceException) GetError() (v string) {
	return p.Error_
}
func (p *ServiceException) SetStatusCode(val int32) {
	p.StatusCode = val
}
func (p *ServiceException) SetError(val string) {
	p.Error_ = val
}

func (p *ServiceException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServiceException(%+v)", *p)
}
func (p *ServiceException) Error() string {
	return p.String()
}

var fieldIDToName_ServiceException = map[int16]string{
	1: "status_code",
	2: "error",
}

type EdgeService interface {
	Health(ctx context.Context) (r *HealthResponse, err error)

	GetRollcalls(ctx context.Context) (r []*Rollcall, err error)

	GetPauseState(ctx context.Context) (r *PauseState, err error)

	SetPause(ctx context.Context, req *SetPauseRequest) (r *SetPauseResponse, err error)

	QRCheckin(ctx context.Context, req *QRCheckinRequest) (r *OperationResponse, err error)

	NumberCheckin(ctx context.Context, req *NumberCheckinRequest) (r *OperationResponse, err error)

	LocationCheckin(ctx context.Context, req *LocationCheckinRequest) (r *OperationResponse, err error)

	BatchQRCheckin(ctx context.Context, req *BatchQRCheckinRequest) (r *BatchQRCheckinResponse, err error)
}

type EdgeServiceHealthArgs struct {
}

func NewEdgeServiceHealthArgs() *EdgeServiceHealthArgs {
	return &EdgeServiceHealthArgs{}
}

func (p *EdgeServiceHealthArgs) InitDefault() {
}

func (p *EdgeServiceHealthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceHealthArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceHealthArgs = map[int16]string{}

type EdgeServiceHealthResult struct {
	Success *HealthResponse   `thrift:"success,0,optional" frugal:"0,optional,HealthResponse" json:"success,omitempty"`
	Ex      *ServiceException `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceHealthResult() *EdgeServiceHealthResult {
	return &EdgeServiceHealthResult{}
}

func (p *EdgeServiceHealthResult) InitDefault() {
}

var EdgeServiceHealthResult_Success_DEFAULT *HealthResponse

func (p *EdgeServiceHealthResult) GetSuccess() (v *HealthResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceHealthResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceHealthResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceHealthResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceHealthResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceHealthResult) SetSuccess(x interface{}) {
	p.Success = x.(*HealthResponse)
}
func (p *EdgeServiceHealthResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceHealthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceHealthResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceHealthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceHealthResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceHealthResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceGetRollcallsArgs struct {
}

func NewEdgeServiceGetRollcallsArgs() *EdgeServiceGetRollcallsArgs {
	return &EdgeServiceGetRollcallsArgs{}
}

func (p *EdgeServiceGetRollcallsArgs) InitDefault() {
}

func (p *EdgeServiceGetRollcallsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceGetRollcallsArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceGetRollcallsArgs = map[int16]string{}

type EdgeServiceGetRollcallsResult struct {
	Success []*Rollcall       `thrift:"success,0,optional" frugal:"0,optional,list<Rollcall>" json:"success,omitempty"`
	Ex      *ServiceException `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceGetRollcallsResult() *EdgeServiceGetRollcallsResult {
	return &EdgeServiceGetRollcallsResult{}
}

func (p *EdgeServiceGetRollcallsResult) InitDefault() {
}

var EdgeServiceGetRollcallsResult_Success_DEFAULT []*Rollcall

func (p *EdgeServiceGetRollcallsResult) GetSuccess() (v []*Rollcall) {
	if !p.IsSetSuccess() {
		return EdgeServiceGetRollcallsResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceGetRollcallsResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceGetRollcallsResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceGetRollcallsResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceGetRollcallsResult) SetSuccess(x interface{}) {
	p.Success = x.([]*Rollcall)
}
func (p *EdgeServiceGetRollcallsResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceGetRollcallsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceGetRollcallsResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceGetRollcallsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceGetRollcallsResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceGetRollcallsResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceGetPauseStateArgs struct {
}

func NewEdgeServiceGetPauseStateArgs() *EdgeServiceGetPauseStateArgs {
	return &EdgeServiceGetPauseStateArgs{}
}

func (p *EdgeServiceGetPauseStateArgs) InitDefault() {
}

func (p *EdgeServiceGetPauseStateArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceGetPauseStateArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceGetPauseStateArgs = map[int16]string{}

type EdgeServiceGetPauseStateResult struct {
	Success *PauseState       `thrift:"success,0,optional" frugal:"0,optional,PauseState" json:"success,omitempty"`
	Ex      *ServiceException `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceGetPauseStateResult() *EdgeServiceGetPauseStateResult {
	return &EdgeServiceGetPauseStateResult{}
}

func (p *EdgeServiceGetPauseStateResult) InitDefault() {
}

var EdgeServiceGetPauseStateResult_Success_DEFAULT *PauseState

func (p *EdgeServiceGetPauseStateResult) GetSuccess() (v *PauseState) {
	if !p.IsSetSuccess() {
		return EdgeServiceGetPauseStateResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceGetPauseStateResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceGetPauseStateResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceGetPauseStateResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceGetPauseStateResult) SetSuccess(x interface{}) {
	p.Success = x.(*PauseState)
}
func (p *EdgeServiceGetPauseStateResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceGetPauseStateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceGetPauseStateResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceGetPauseStateResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceGetPauseStateResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceGetPauseStateResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceSetPauseArgs struct {
	Req *SetPauseRequest `thrift:"req,1" frugal:"1,default,SetPauseRequest" json:"req"`
}

func NewEdgeServiceSetPauseArgs() *EdgeServiceSetPauseArgs {
	return &EdgeServiceSetPauseArgs{}
}

func (p *EdgeServiceSetPauseArgs) InitDefault() {
}

var EdgeServiceSetPauseArgs_Req_DEFAULT *SetPauseRequest

func (p *EdgeServiceSetPauseArgs) GetReq() (v *SetPauseRequest) {
	if !p.IsSetReq() {
		return EdgeServiceSetPauseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EdgeServiceSetPauseArgs) SetReq(val *SetPauseRequest) {
	p.Req = val
}

func (p *EdgeServiceSetPauseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EdgeServiceSetPauseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceSetPauseArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceSetPauseArgs = map[int16]string{
	1: "req",
}

type EdgeServiceSetPauseResult struct {
	Success *SetPauseResponse `thrift:"success,0,optional" frugal:"0,optional,SetPauseResponse" json:"success,omitempty"`
	Ex      *ServiceException `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceSetPauseResult() *EdgeServiceSetPauseResult {
	return &EdgeServiceSetPauseResult{}
}

func (p *EdgeServiceSetPauseResult) InitDefault() {
}

var EdgeServiceSetPauseResult_Success_DEFAULT *SetPauseResponse

func (p *EdgeServiceSetPauseResult) GetSuccess() (v *SetPauseResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceSetPauseResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceSetPauseResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceSetPauseResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceSetPauseResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceSetPauseResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetPauseResponse)
}
func (p *EdgeServiceSetPauseResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceSetPauseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceSetPauseResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceSetPauseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceSetPauseResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceSetPauseResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceQRCheckinArgs struct {
	Req *QRCheckinRequest `thrift:"req,1" frugal:"1,default,QRCheckinRequest" json:"req"`
}

func NewEdgeServiceQRCheckinArgs() *EdgeServiceQRCheckinArgs {
	return &EdgeServiceQRCheckinArgs{}
}

func (p *EdgeServiceQRCheckinArgs) InitDefault() {
}

var EdgeServiceQRCheckinArgs_Req_DEFAULT *QRCheckinRequest

func (p *EdgeServiceQRCheckinArgs) GetReq() (v *QRCheckinRequest) {
	if !p.IsSetReq() {
		return EdgeServiceQRCheckinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EdgeServiceQRCheckinArgs) SetReq(val *QRCheckinRequest) {
	p.Req = val
}

func (p *EdgeServiceQRCheckinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EdgeServiceQRCheckinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceQRCheckinArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceQRCheckinArgs = map[int16]string{
	1: "req",
}

type EdgeServiceQRCheckinResult struct {
	Success *OperationResponse `thrift:"success,0,optional" frugal:"0,optional,OperationResponse" json:"success,omitempty"`
	Ex      *ServiceException  `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceQRCheckinResult() *EdgeServiceQRCheckinResult {
	return &EdgeServiceQRCheckinResult{}
}

func (p *EdgeServiceQRCheckinResult) InitDefault() {
}

var EdgeServiceQRCheckinResult_Success_DEFAULT *OperationResponse

func (p *EdgeServiceQRCheckinResult) GetSuccess() (v *OperationResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceQRCheckinResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceQRCheckinResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceQRCheckinResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceQRCheckinResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceQRCheckinResult) SetSuccess(x interface{}) {
	p.Success = x.(*OperationResponse)
}
func (p *EdgeServiceQRCheckinResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceQRCheckinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceQRCheckinResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceQRCheckinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceQRCheckinResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceQRCheckinResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceNumberCheckinArgs struct {
	Req *NumberCheckinRequest `thrift:"req,1" frugal:"1,default,NumberCheckinRequest" json:"req"`
}

func NewEdgeServiceNumberCheckinArgs() *EdgeServiceNumberCheckinArgs {
	return &EdgeServiceNumberCheckinArgs{}
}

func (p *EdgeServiceNumberCheckinArgs) InitDefault() {
}

var EdgeServiceNumberCheckinArgs_Req_DEFAULT *NumberCheckinRequest

func (p *EdgeServiceNumberCheckinArgs) GetReq() (v *NumberCheckinRequest) {
	if !p.IsSetReq() {
		return EdgeServiceNumberCheckinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EdgeServiceNumberCheckinArgs) SetReq(val *NumberCheckinRequest) {
	p.Req = val
}

func (p *EdgeServiceNumberCheckinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EdgeServiceNumberCheckinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceNumberCheckinArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceNumberCheckinArgs = map[int16]string{
	1: "req",
}

type EdgeServiceNumberCheckinResult struct {
	Success *OperationResponse `thrift:"success,0,optional" frugal:"0,optional,OperationResponse" json:"success,omitempty"`
	Ex      *ServiceException  `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceNumberCheckinResult() *EdgeServiceNumberCheckinResult {
	return &EdgeServiceNumberCheckinResult{}
}

func (p *EdgeServiceNumberCheckinResult) InitDefault() {
}

var EdgeServiceNumberCheckinResult_Success_DEFAULT *OperationResponse

func (p *EdgeServiceNumberCheckinResult) GetSuccess() (v *OperationResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceNumberCheckinResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceNumberCheckinResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceNumberCheckinResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceNumberCheckinResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceNumberCheckinResult) SetSuccess(x interface{}) {
	p.Success = x.(*OperationResponse)
}
func (p *EdgeServiceNumberCheckinResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceNumberCheckinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceNumberCheckinResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceNumberCheckinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceNumberCheckinResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceNumberCheckinResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceLocationCheckinArgs struct {
	Req *LocationCheckinRequest `thrift:"req,1" frugal:"1,default,LocationCheckinRequest" json:"req"`
}

func NewEdgeServiceLocationCheckinArgs() *EdgeServiceLocationCheckinArgs {
	return &EdgeServiceLocationCheckinArgs{}
}

func (p *EdgeServiceLocationCheckinArgs) InitDefault() {
}

var EdgeServiceLocationCheckinArgs_Req_DEFAULT *LocationCheckinRequest

func (p *EdgeServiceLocationCheckinArgs) GetReq() (v *LocationCheckinRequest) {
	if !p.IsSetReq() {
		return EdgeServiceLocationCheckinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EdgeServiceLocationCheckinArgs) SetReq(val *LocationCheckinRequest) {
	p.Req = val
}

func (p *EdgeServiceLocationCheckinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EdgeServiceLocationCheckinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceLocationCheckinArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceLocationCheckinArgs = map[int16]string{
	1: "req",
}

type EdgeServiceLocationCheckinResult struct {
	Success *OperationResponse `thrift:"success,0,optional" frugal:"0,optional,OperationResponse" json:"success,omitempty"`
	Ex      *ServiceException  `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceLocationCheckinResult() *EdgeServiceLocationCheckinResult {
	return &EdgeServiceLocationCheckinResult{}
}

func (p *EdgeServiceLocationCheckinResult) InitDefault() {
}

var EdgeServiceLocationCheckinResult_Success_DEFAULT *OperationResponse

func (p *EdgeServiceLocationCheckinResult) GetSuccess() (v *OperationResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceLocationCheckinResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceLocationCheckinResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceLocationCheckinResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceLocationCheckinResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceLocationCheckinResult) SetSuccess(x interface{}) {
	p.Success = x.(*OperationResponse)
}
func (p *EdgeServiceLocationCheckinResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceLocationCheckinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceLocationCheckinResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceLocationCheckinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceLocationCheckinResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceLocationCheckinResult = map[int16]string{
	0: "success",
	1: "ex",
}

type EdgeServiceBatchQRCheckinArgs struct {
	Req *BatchQRCheckinRequest `thrift:"req,1" frugal:"1,default,BatchQRCheckinRequest" json:"req"`
}

func NewEdgeServiceBatchQRCheckinArgs() *EdgeServiceBatchQRCheckinArgs {
	return &EdgeServiceBatchQRCheckinArgs{}
}

func (p *EdgeServiceBatchQRCheckinArgs) InitDefault() {
}

var EdgeServiceBatchQRCheckinArgs_Req_DEFAULT *BatchQRCheckinRequest

func (p *EdgeServiceBatchQRCheckinArgs) GetReq() (v *BatchQRCheckinRequest) {
	if !p.IsSetReq() {
		return EdgeServiceBatchQRCheckinArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *EdgeServiceBatchQRCheckinArgs) SetReq(val *BatchQRCheckinRequest) {
	p.Req = val
}

func (p *EdgeServiceBatchQRCheckinArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EdgeServiceBatchQRCheckinArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceBatchQRCheckinArgs(%+v)", *p)
}

var fieldIDToName_EdgeServiceBatchQRCheckinArgs = map[int16]string{
	1: "req",
}

type EdgeServiceBatchQRCheckinResult struct {
	Success *BatchQRCheckinResponse `thrift:"success,0,optional" frugal:"0,optional,BatchQRCheckinResponse" json:"success,omitempty"`
	Ex      *ServiceException       `thrift:"ex,1,optional" frugal:"1,optional,ServiceException" json:"ex,omitempty"`
}

func NewEdgeServiceBatchQRCheckinResult() *EdgeServiceBatchQRCheckinResult {
	return &EdgeServiceBatchQRCheckinResult{}
}

func (p *EdgeServiceBatchQRCheckinResult) InitDefault() {
}

var EdgeServiceBatchQRCheckinResult_Success_DEFAULT *BatchQRCheckinResponse

func (p *EdgeServiceBatchQRCheckinResult) GetSuccess() (v *BatchQRCheckinResponse) {
	if !p.IsSetSuccess() {
		return EdgeServiceBatchQRCheckinResult_Success_DEFAULT
	}
	return p.Success
}

var EdgeServiceBatchQRCheckinResult_Ex_DEFAULT *ServiceException

func (p *EdgeServiceBatchQRCheckinResult) GetEx() (v *ServiceException) {
	if !p.IsSetEx() {
		return EdgeServiceBatchQRCheckinResult_Ex_DEFAULT
	}
	return p.Ex
}
func (p *EdgeServiceBatchQRCheckinResult) SetSuccess(x interface{}) {
	p.Success = x.(*BatchQRCheckinResponse)
}
func (p *EdgeServiceBatchQRCheckinResult) SetEx(val *ServiceException) {
	p.Ex = val
}

func (p *EdgeServiceBatchQRCheckinResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EdgeServiceBatchQRCheckinResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *EdgeServiceBatchQRCheckinResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EdgeServiceBatchQRCheckinResult(%+v)", *p)
}

var fieldIDToName_EdgeServiceBatchQRCheckinResult = map[int16]string{
	0: "success",
	1: "ex",
}

// exceptions of methods in EdgeService.
var (
	_ error = (*ServiceException)(nil)
)
